import { DM_Sans } from "next/font/google";
import "./globals.css";
import Navbar from "../Components/Navbar";
import ThemeProvider from "@/Context/ThemeContext";
import Footer from "@/Components/Footer";


const dmSans = DM_Sans({
  variable: "--font-dm-sans",
  subsets: ["latin"],
  weight: ["400", "500", "700"],
});

export const metadata = {
  title: "Shajid International",
  description: "Generated by create next app",
  icons: {
    icon: "/Shajid-International-Favicon.png",
  },
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${dmSans.variable} font-mono antialiased`}
      >
        <ThemeProvider>
          <Navbar />
          {children}
          <Footer />
        </ThemeProvider>
      </body>
    </html>
  );
}
